name: CI/CD Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/wisecow:latest .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/wisecow:latest

      # Step 6: Deploy to Kubernetes (Kind Cluster)
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3

      - name: Deploy Wisecow to K8s
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
